fancybox: true ## If you want to use fancybox please set the value to true.
# duoshuo: mjd507 ## Your duoshuo_shortname, e.g. username
# disqus: ## Your disqus_shortname, e.g. username
# google_search: true ## Use Google search, true/false.
# baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: ## Use a jQuery-based local search engine, true/false.
# google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 1c847d4fb515d19b6108f15a5387f1d6 ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
shareto: false ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

# Gitalk
gitalk: 
  enable: true
  client_id: 'fa8d49cc90698365347d'
  client_secret: 'ad101f458b7f3950fccc09b931977c106cd2c467'
  repo: 'mjd507.github.io'
  owner: 'mjd507'
  admin: 'mjd507'
  distractionFreeMode: false

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  # - page: about
  #   directory: about/
  #   icon: fa-user
  # - page: readingList
  #   directory: readingList/
  #   icon: fa-th-large
  # - page: dailyProject
  #   directory: 365/
  #   icon: fa-fire

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  # - search
  - category
  # - tag
  # - recent_posts
  # - recent_comments
  - links

links:
 - title: JohnnyShieh
   url: http://johnnyshieh.me/
 - title: 代码家
   url: https://daimajia.com/
 - title: Jerry Qu
   url: https://imququ.com/
 - title: Derek Sivers
   url: https://sivers.org/
 - title: alispittel
   url: https://www.alispit.tel/#/
 - title: Hugo Gu
   url: http://www.hugogu.cn/
 - title: 奇舞周刊
   url: https://weekly.75team.com/

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

# Static files
js: js
css: css

# Theme version
version: 0.0.0
